import axl.lang.Axolotl;
import axl.lang.Exception;

public class Main {

    public static void main(String[] args) throws Exception {
        Axolotl.$init(); // generated by the compiler

        throw new Exception();
    }
}