package axl;

import axl.lang.Axolotl;
import axl.lang.Exception;
import axl.lang.GotoException;
import axl.lang.GotoUtils;

public class Main {
    public static void functionD() throws GotoException {
        GotoUtils.go("E", "Ban!");
    }

    public static void functionC() throws GotoException {
        System.out.println("C start!");
        GotoUtils.go("A", "Hello from C!");
        System.out.println("C end!");
    }

    public static void functionB() throws GotoException {
        System.out.println("B start!");
        System.out.println(GotoUtils.label("B", () -> {
            functionC();
        }));
        System.out.println("B end!");
    }

    public static void functionA() throws GotoException {
        System.out.println("A start!");
        System.out.println(GotoUtils.label("A", () -> {
            functionB();
        }));
        System.out.println("A end!");
    }

    public static void main(String[] args) throws Exception, GotoException {
        Axolotl.$init(); // generated by the compiler

        functionA();
        functionD();
    }
}